version: '3.9'

services:
  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
#    restart: unless-stopped
    volumes:
      - ./volume/${VERSION}/www:/var/www/html
      - ./volume/${VERSION}/db/sqlite:/var/roundcube/db
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mailserver
      # - ROUNDCUBEMAIL_SMTP_PORT=10993
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mailserver

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.beeclover.io
    ports:
      - "25:25"
      - "465:465"
      - "993:993"
      - "4190:4190"
      - "11334:11334"
    volumes:
      - ./volume/${VERSION}/dms/mail-data/:/var/mail/
      - ./volume/${VERSION}/dms/mail-state/:/var/mail-state/
      - ./volume/${VERSION}/dms/mail-logs/:/var/log/mail/
      - ./volume/${VERSION}/dms/config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
