version: '3.9'

networks:
  traefik_proxy:
    external: true

services:
  whoami:
    image: docker.io/traefik/whoami:latest
    networks:
      - traefik_proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.mail.rule=Host(`${MAIL_DOMAIN}`)
      - traefik.http.routers.mail.entrypoints=https
      - traefik.http.routers.mail.tls.certresolver=leresolver
      - traefik.http.services.mail.loadbalancer.server.port=80
  roundcubemail:
    networks:
      - traefik_proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailclient.rule=Host(`${MAIL_CLIENT_DOMAIN}`)
      - traefik.http.routers.mailclient.entrypoints=https
      - traefik.http.routers.mailclient.tls.certresolver=leresolver
      - traefik.http.services.mailclient.loadbalancer.server.port=80
  # mailserver:
  #   volumes:
  #      - ../../svc/traefik/traefik/acme/acme.json:/etc/letsencrypt/acme.json:ro
  #   environment:
  #     SSL_TYPE: letsencrypt
  #     SSL_DOMAIN: mail.beeclover.io
      # for a wildcard certificate, use
      # SSL_DOMAIN: example.com
    # networks:
    #   - traefik_proxy
    #   - default
    # labels:
    #   - traefik.enable=true
    #   - traefik.tcp.routers.smtp.rule=HostSNI(`*`)
    #   - traefik.tcp.routers.smtp.entrypoints=smtp
    #   - traefik.tcp.routers.smtp.service=smtp
    #   - traefik.tcp.services.smtp.loadbalancer.server.port=25
    #   - traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=1
    #   - traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`)
    #   - traefik.tcp.routers.smtp-ssl.tls=false
    #   - traefik.tcp.routers.smtp-ssl.entrypoints=smtp-ssl
    #   - traefik.tcp.routers.smtp-ssl.service=smtp-ssl
    #   - traefik.tcp.services.smtp-ssl.loadbalancer.server.port=465
    #   - traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=1
    #   - traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)
    #   - traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl
    #   - traefik.tcp.routers.imap-ssl.service=imap-ssl
    #   - traefik.tcp.services.imap-ssl.loadbalancer.server.port=10993
    #   - traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2
    #   - traefik.tcp.routers.sieve.rule=HostSNI(`*`)
    #   - traefik.tcp.routers.sieve.entrypoints=sieve
    #   - traefik.tcp.routers.sieve.service=sieve
    #   - traefik.tcp.services.sieve.loadbalancer.server.port=4190
  